# Generated by Django 4.2.2 on 2023-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_in_metres', models.FloatField(blank=True, null=True)),
                ('weight_in_kg', models.FloatField(blank=True, null=True)),
                ('date_measured', models.DateField()),
            ],
        ),
    ]
