# Generated by Django 4.2.2 on 2023-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0002_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='bmi_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
