# Generated by Django 4.2.2 on 2023-06-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0003_bmi_bmi_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmi',
            old_name='bmi_value',
            new_name='bmi',
        ),
        migrations.RenameField(
            model_name='bmi',
            old_name='date_measured',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bmi',
            old_name='height_in_metres',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='bmi',
            old_name='weight_in_kg',
            new_name='weight',
        ),
    ]
