# Generated by Django 4.2.2 on 2023-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessApp', '0004_rename_bmi_value_bmi_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
